version: "2"
services:
  api:
    build:
       context: .
    expose:
      - "80"
    ports:
      - "8081:80"
    command: "npm start"
    depends_on:
      - db
  db:
    image: "mongo"
    expose:
      - "27017"
