version: "2"
services:
  api:
    build:
      context: .
    environment:
      - NODE_ENV=debug
      - API_PORT=80
      - API_HOST=db
      - CLIENT_URL=http://localhost:3000
      - DEBUG="temnames:*"
    expose:
      - "80"
    ports:
      - "8081:80"
    command: "npm start"
    depends_on:
      - db
  db:
    image: "mongo"
    expose:
      - "27017"
