version: "2"
services:
  api:
    image: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=debug
      - API_PORT=80
      - CORS_FROM=http://localhost:4200
      - DEBUG="temnames:*"
    volumes:
      - ./:/home/node/app
    expose:
      - "80"
    ports:
      - "8081:80"
    command: "npm start"
  db:
    image: "mongo"
    expose:
      - "27017"
